# Auto-generated by seed/glue/create.sh — sample glueetl script.
# Reads from the JDBC connection smus-mig-seed-jdbc-conn and writes a no-op
# DataFrame back to s3://smus-mig-seed-glue-data-123456789012-us-east-1/etl-output/.
import sys
from awsglue.context import GlueContext
from awsglue.job import Job
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext

args = getResolvedOptions(sys.argv, ["JOB_NAME"])
sc = SparkContext()
glue = GlueContext(sc)
job = Job(glue)
job.init(args["JOB_NAME"], args)
job.commit()
