# Auto-generated by seed/glue/create.sh — sample pythonshell script.
# Pythonshell jobs run a single Python file with the standard library
# and a small set of preinstalled wheels (pandas, numpy, boto3). This
# script is a no-op so Step 4 has a real ScriptLocation to inspect.
print("seed pythonshell job: noop")
